name: 'Setup ksnotify'
description: 'Setup ksnotify CLI tool for kubectl diff notification'
author: 'kitagry'

branding:
  icon: 'bell'
  color: 'blue'

inputs:
  version:
    description: 'Version of ksnotify to install (default: latest)'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Install ksnotify
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        if [ "$VERSION" = "latest" ]; then
          VERSION=$(curl -s https://api.github.com/repos/hirosassa/ksnotify/releases/latest | jq -r .tag_name)
        fi

        # Detect OS and architecture
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m)
        case $ARCH in
          x86_64) ARCH="amd64" ;;
          aarch64) ARCH="arm64" ;;
          arm64) ARCH="arm64" ;;
        esac

        # Download and install ksnotify
        DOWNLOAD_URL="https://github.com/hirosassa/ksnotify/releases/download/${VERSION}/ksnotify_${OS}_${ARCH}.tar.gz"
        curl -sL "$DOWNLOAD_URL" | tar -xz -C /tmp

        # Make executable and move to PATH
        chmod +x /tmp/ksnotify
        sudo mv /tmp/ksnotify /usr/local/bin/

        echo "ksnotify installed successfully"
        ksnotify --version
