name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Generate changelog
        id: changelog
        run: |
          # 前回のタグから今回までの変更を取得
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD~1 2>/dev/null || echo "")
          if [ -n "$PREVIOUS_TAG" ]; then
            CHANGES=$(git log --pretty=format:"- %s" $PREVIOUS_TAG..HEAD)
          else
            CHANGES=$(git log --pretty=format:"- %s")
          fi

          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update major version tag
        run: |
          # v1.2.3 -> v1 のようにメジャーバージョンタグを更新
          MAJOR_VERSION=$(echo ${{ github.ref_name }} | cut -d. -f1)
          git tag -fa $MAJOR_VERSION -m "Update $MAJOR_VERSION to ${{ github.ref_name }}"
          git push origin $MAJOR_VERSION --force
